version: 0.2

phases:
  install:
    commands:
      - echo "Installing"
  pre_build:
    commands:
      - echo "Prebuilding"
  build:
    commands:
      - echo "Building"
  post_build:
    commands:
      - echo "Post-building"